name: Frontend Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Run unit tests
      run: |
        node -v
        npm -v
        NODE_ENV=test NODE_DEBUG=crypto,module npm run test:unit -- --run --reporter verbose
      env:
        NODE_OPTIONS: --experimental-vm-modules --trace-warnings
        DEBUG: '*'
        VITEST_MAX_THREADS: 1

    - name: Run linter
      run: npm run lint

    - name: Type check
      run: npm run type-check 